---
apiVersion: v1
kind: Service
metadata:
  namespace: flask-ns
  name: game-2048-service
  annotations:
    cloud: aws
spec:
  selector:
    app: game-2048-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  clusterIP: 10.100.100.101
  internalTrafficPolicy: "Cluster"
...
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flask-ns
  name: game-2048-deployment
  labels:
    name: game-2048-deployment
  annotations:
    name: game-2048-deployment
spec:
  selector:
    matchLabels:
      app: game-2048-app
  replicas: 2
  template:
    metadata:
      labels:
        app: game-2048-app
    spec:
      containers:
      - image: public.ecr.aws/l6m2t8p7/docker-2048:latest
        imagePullPolicy: Always
        name: game-2048-app
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 150Mi
              cpu: 250m
      restartPolicy: "Always"
  minReadySeconds: 3
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: "20%"
      maxUnavailable: "20%"
  revisionHistoryLimit: 8
  progressDeadlineSeconds: 600
  paused: false
...