apiVersion: v1
kind: Service
metadata:
  namespace: {{ required "Namespace is required" .Values.app.ns | lower | quote }}
  name: {{ required "service name" .Values.app.gameServiceName | lower | quote }}
  annotations:
    cloud: aws
spec:
  selector:
    app: game-2048-app
  ports:
    - port: {{ default 80 .Values.app.servicePort }}
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  ipFamilies: 
    - "IPv4"
  ipFamilyPolicy: "SingleStack"
  clusterIP: {{ .Values.app.gameClusterIp }}
  internalTrafficPolicy: "Cluster"